[project]
authors = ["mac"]
entry = "main.sw"
license = "Apache-2.0"
name = "asset"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.4.4" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }
