# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: lend_vault
ecosystem: fuel
networks:
- id: 0
  start_block: 0
  contracts:
  - name: LendVault
    address:
    - 0xd81f433402a8ae93b9d88a02b05d6e03f517c02331a01d402191f638af31e147
    abi_file_path: abis/lendvault-abi.json
    handler: src/EventHandlers.ts
    events:
    - name: Withdraw
      logId: '7130535457264345996'
    - name: LoanReturned
      logId: '71438831326827251'
    - name: StrLog
      logId: '10098701174489624218'
    - name: BorrowLog
      logId: '15810891269556875121'
    - name: Deposit
      logId: '13151976532709238696'
