# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio_lend_vault
ecosystem: fuel
networks:
- id: 0
  start_block: 0
  contracts:
  - name: LendVault
    address:
    - 0x327bc94d3a7459fd1e06ca469d1df40c5d310897d62295b6df35bbe649aa15e4
    abi_file_path: abis/lendvault-abi.json
    handler: src/EventHandlers.ts
    events:
    - name: Withdraw
      logId: '7130535457264345996'
    - name: StrLog
      logId: '10098701174489624218'
    - name: LoanReturned
      logId: '71438831326827251'
    - name: Deposit
      logId: '13151976532709238696'
    - name: BorrowLog
      logId: '15810891269556875121'
