# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: LendVault
ecosystem: fuel
networks:
- id: 0
  start_block: 0
  contracts:
  - name: LendVault
    address:
    - 0xaead338685ebfa6425c67e879da687f86e51c56ee6e7f51e9f21fe026a9ff9e1
    abi_file_path: abis/lendvault-abi.json
    handler: src/EventHandlers.ts
    events:
    - name: Withdraw
      logId: '7130535457264345996'
    - name: Deposit
      logId: '13151976532709238696'
    - name: StrLog
      logId: '10098701174489624218'
    - name: BorrowLog
      logId: '15810891269556875121'
    - name: LoanReturned
      logId: '71438831326827251'
